package:
    name: abstractrendering-java
    version: "dev_snapshot"

source:
    git_rev: 03c8f1019d703702ea7313c01028faa9f5fd8945
    git_url: https://github.com/JosephCottam/AbstractRendering.git

build:
    number: 0

# need a Java install for build/run

