package:
    name: abstractrendering-java
    version: "0.1"

source:
    git_rev: 14efc3bfee82a7b64f6c5d0e868c975043cd7f48
    #    git_url: https://github.com/JosephCottam/AbstractRendering.git (Built against a patched version downstream of this repo)
    git_url: https://github.com/ahmadia/AbstractRendering.git

build:
    number: 0

# need a Java install for build/run

